In [1]:
import seaborn as sns
from sklearn.model_selection import KFold
import matplotlib.pyplot as plt

from scipy import stats
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from formulaic import model_matrix

In [ ]:
#import os
#print(pwd)
#os.chdir('./notebooks')

# Limpieza de Datos

En Python, las funciones y paquetes para trabajar con datos no están pensadas para poder hacerlas "sin saber nada de Python". Al contrario, muchas operaciones sencillas de DataFrames requieren conocer técnicas de programación en Python. Vamos a ver algunas en esta clase, principalmente estas cuatro:
1. Diccionarios
2. Encadenamiento de métodos
3. Funciones lambda
4. Definición de listas por comprensión (parte 2)

### **Ejercicio** 

En el dataset de vinos, renombrar la columna "od280/od315_of_diluted_wines" a "od280_od315_of_diluted_wines".

In [2]:
from sklearn.datasets import load_wine
wine = load_wine(as_frame=True)
wineData = wine.data
wineData.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

Hay esencialmente dos formas de renombrar columnas:
1. Utilizar `rename()`
2. Modificar la lista de nombres de columnas `dataframe.columns`

Comenzamos con `rename()`.

In [3]:
pd.DataFrame.rename??

# O help(pd.DataFrame.rename)
# O wineData.rename??

Signature:
pd.DataFrame.rename(
    self,
    mapper: 'Renamer | None' = None,
    *,
    index: 'Renamer | None' = None,
    columns: 'Renamer | None' = None,
    axis: 'Axis | None' = None,
    copy: 'bool | lib.NoDefault' = <no_default>,
    inplace: 'bool' = False,
    level: 'Level | None' = None,
    errors: 'IgnoreRaise' = 'ignore',
) -> 'DataFrame | None'
Source:
    def rename(
        self,
        mapper: Renamer | None = None,
        *,
        index: Renamer | None = None,
        columns: Renamer | None = None,
        axis: Axis | None = None,
        copy: bool | lib.NoDefault = lib.no_default,
        inplace: bool = False,
        level: Level | None = None,
        errors: IgnoreRaise = "ignore",
    ) -> DataFrame | None:
        """
        Rename columns or index labels.

        Function / dict values must be unique (1-to-1). Labels not contained in
        a dict / Series will be left as-is. Extra labels listed don't throw an
        error.

        See the :ref:`user guide <basics.rename>` for more.

        Parameters
        ----------
        mapper : dict-like or function
            Dict-like or function transformations to apply to
            that axis' values. Use either ``mapper`` and ``axis`` to
            specify the axis to target with ``mapper``, or ``index`` and
            ``columns``.
        index : dict-like or function
            Alternative to specifying axis (``mapper, axis=0``
            is equivalent to ``index=mapper``).
        columns : dict-like or function
            Alternative to specifying axis (``mapper, axis=1``
            is equivalent to ``columns=mapper``).
        axis : {0 or 'index', 1 or 'columns'}, default 0
            Axis to target with ``mapper``. Can be either the axis name
            ('index', 'columns') or number (0, 1). The default is 'index'.
        copy : bool, default False
            This keyword is now ignored; changing its value will have no
            impact on the method.

            .. deprecated:: 3.0.0

                This keyword is ignored and will be removed in pandas 4.0. Since
                pandas 3.0, this method always returns a new object using a lazy
                copy mechanism that defers copies until necessary
                (Copy-on-Write). See the `user guide on Copy-on-Write
                <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
                for more details.

        inplace : bool, default False
            Whether to modify the DataFrame rather than creating a new one.
            If True then value of copy is ignored.
        level : int or level name, default None
            In case of a MultiIndex, only rename labels in the specified
            level.
        errors : {'ignore', 'raise'}, default 'ignore'
            If 'raise', raise a `KeyError` when a dict-like `mapper`, `index`,
            or `columns` contains labels that are not present in the Index
            being transformed.
            If 'ignore', existing keys will be renamed and extra keys will be
            ignored.

        Returns
        -------
        DataFrame or None
            DataFrame with the renamed axis labels or None if ``inplace=True``.

        Raises
        ------
        KeyError
            If any of the labels is not found in the selected axis and
            "errors='raise'".

        See Also
        --------
        DataFrame.rename_axis : Set the name of the axis.

        Examples
        --------
        ``DataFrame.rename`` supports two calling conventions

        * ``(index=index_mapper, columns=columns_mapper, ...)``
        * ``(mapper, axis={'index', 'columns'}, ...)``

        We *highly* recommend using keyword arguments to clarify your
        intent.

        Rename columns using a mapping:

        >>> df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
        >>> df.rename(columns={"A": "a", "B": "c"})
           a  c
        0  1  4
        1  2  5
        2  3  6

        Rename index using a mapping:

        >>> df.rename(index={0: "x", 1: "y", 2: "z"})
           A  B
        x  1  4
        y  2  5
        z  3  6

        Cast index labels to a different type:

        >>> df.index
        RangeIndex(start=0, stop=3, step=1)
        >>> df.rename(index=str).index
        Index(['0', '1', '2'], dtype='str')

        >>> df.rename(columns={"A": "a", "B": "b", "C": "c"}, errors="raise")
        Traceback (most recent call last):
        KeyError: ['C'] not found in axis

        Using axis-style parameters:

        >>> df.rename(str.lower, axis="columns")
           a  b
        0  1  4
        1  2  5
        2  3  6

        >>> df.rename({1: 2, 2: 4}, axis="index")
           A  B
        0  1  4
        2  2  5
        4  3  6
        """
        self._check_copy_deprecation(copy)
        return super()._rename(
            mapper=mapper,
            index=index,
            columns=columns,
            axis=axis,
            inplace=inplace,
            level=level,
            errors=errors,
        )
File:      ~/uba-compu-y-datos/laboratorio-de-datos-1c2026/.venv/lib/python3.14/site-packages/pandas/core/frame.py
Type:      function

Vemos que podemos renombrar columnas utilizando `columns: dict-like or function`

## 1. Diccionarios
Los diccionarios se utilizan para almacenar valores de datos en pares clave:valor.

Un diccionario es una colección ordenada, modificable y que no permite duplicados.

In [4]:
# Ejemplo
dict = { "hola" : "Expresión de saludo utilizada entre dos o más personas de trato familiar", "cinco" : 5, "dias" : ["lunes", "martes", "miercoles"]}

In [5]:
dict["cinco"]

5

In [6]:
# Ejemplo
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict["brand"])

Ford

Para renombrar una columna, usamos rename(columns = _DICT_) y un diccionario con "nombre viejo" como claves y "nombre nuevo" como valores.

In [7]:
wineData.rename(columns = {"od280/od315_of_diluted_wines" : "od280_od315_of_diluted_wines"})  # No es necesario renombrar todas las columnas, podemos renombrar las que querramos.

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280_od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [9]:
# Cambió algo? --< No porque no lo hizo sobre el dataframe original
wineData

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [10]:
# Podemos guardar los cambios en el mismo DataFrame o en uno nuevo
wineClean = wineData.rename(columns = {"od280/od315_of_diluted_wines" : "od280_od315_of_diluted_wines"})
wineClean.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280_od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

**Nota:** también existe la opción "inplace = True" pero no está recomendada (por ejemplo, no permite encadenar comandos).

## `rename` con funciones

También podemos usar funciones para renombrar columnas (Python permite pasar funciones como parámetros).

#### **Ejemplo:** Pasar todos los nombres de columnas a mayúsculas.

In [11]:
# Para pasar un string a mayusculas utilizamo str.upper
str.upper("hola")

'HOLA'

¿Cómo lo usarian para renombrar nuestras variables?

In [ ]:
# Así?
datos.rename(columns = str.upper) # --> ASI, le estoy pasando el nombre de la función para que aplique, no la función con parametros como tal
# o así?
datos.rename(columns = str.upper())

<details>
<summary>Click para ver la respuesta</summary>

Le pasamos el nombre de la función, por eso va sin los paréntesis. 

Si la pasamos con paréntesis le estaríamos pasando el resultado de evaluar la función sin parámetros.
</details>

In [15]:
wineData.rename(columns = str.upper)

,ALCOHOL,MALIC_ACID,ASH,ALCALINITY_OF_ASH,MAGNESIUM,TOTAL_PHENOLS,FLAVANOIDS,NONFLAVANOID_PHENOLS,PROANTHOCYANINS,COLOR_INTENSITY,HUE,OD280/OD315_OF_DILUTED_WINES,PROLINE
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

### Ejercicio

Definiendo tu propia función, agregar en todos los nombres de columna "_2026" al final del nombre.

In [22]:
def agregar_2026(df):
    dict_col_a_reemplazar = {}
    for col in df.columns:
        dict_col_a_reemplazar[col] = col + "_2026"
    return dict_col_a_reemplazar

In [23]:
wineClean = wineData.rename(columns = agregar_2026(wineData))
wineClean

,alcohol_2026,malic_acid_2026,ash_2026,alcalinity_of_ash_2026,magnesium_2026,total_phenols_2026,flavanoids_2026,nonflavanoid_phenols_2026,proanthocyanins_2026,color_intensity_2026,hue_2026,od280/od315_of_diluted_wines_2026,proline_2026
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

## 2. Encadenar métodos

### 2.a Datos faltantes

#### **Ejercicio** 
En la base de datos de pingüinos, eliminar las filas con datos faltantes, y renumerar los índices comenzando en 1.

In [24]:
penguins = sns.load_dataset("penguins")
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

#### Primero: ¿qué son los datos faltantes?

¿Qué significa un valor faltante? Es un dato que por distintos motivos no fue ingresado (por ejemplo si juntamos datos de distintas fuentes, en alguna de las fuentes esa información puede no estar disponible).

Los datos faltantes son algo típico de cualquier pipeline de análisis de datos. En general los paquetes estadísticos (pandas, dplyr, etc) tratan de facilitar el manejo de estos tipos de datos. En Pandas, se utiliza la expresión NaN (Not a number) o NA que viene del mundo R (Not available)

In [26]:
# Vamos a trabajar con una base de eficiencia del sueño
datos = pd.read_csv("../data/Sleep_efficiency_cleaning.csv")
datos

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

Para poder acceder a los datos faltantes, podemos utilizar la función `isna()`

¿Cómo la usamos? ¿Qué nos devuelve? ---> Devuelve el dataframe con el resultado de la comparación logica de _si es un dato faltante o no_.

In [27]:
datos.isna()

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
458,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
459,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
460,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
461,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

¿Cómo podemos transformar toda esta información para que sea más legible?

In [28]:
# Una forma bien simple sería usando 
datos.isna().sum()

ID                         0
Age                        0
Gender                     0
Bedtime                    0
Wakeup time                0
Sleep duration             0
Sleep efficiency           0
REM sleep percentage       0
Deep sleep percentage      0
Light sleep percentage     0
Awakenings                20
Caffeine consumption      25
Alcohol consumption       15
Smoking status             0
Exercise frequency         6
dtype: int64

In [ ]:
# De ahi sabemos que Despertares, Consumo de cafeina, Consumo de alcohol y Frecuencia de ejercicio tienen datos faltantes

In [29]:
# Esto nos da lo mismo (null es comun en SQL, NaN se usa en NumPy)
penguins.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

¿Qué podríamos hacer con todos estos datos faltantes?

In [30]:
# Una posibilidad es usar dropna() 
# ¿Qué les parece que hace esta función? ---> elimina las filas con datos faltantes
# ¿Cuántas filas teniamos antes y cuántas tenemos ahora? ¿Cuáles son las ventajas y desventajas de esto?

datos.dropna()

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

De 462 filas (observaciones) paso a 397, estoy perdiendo cantidad de observaciones cuando uso el .dropna() sobre las filas.

In [31]:
# Otra posibilidad es eliminar las columnas con datos faltantes, de forma de no perder participantes. ¿Cuáles son las ventajas y desventajas de esto?
datos.dropna(axis="columns")

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Smoking status
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,Yes
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,Yes
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,No
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,Yes
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,No
...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,Yes
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,No
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,No
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,No
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,Yes

Aca, en vez de eliminar las filas con datos faltantes, elimino las columnas que tengan datos faltantes: de 15 columnas paso a 11. En vez de eliminar observaciones, elimino variables.

Otra opción es hacer una combinación de estas dos posibilidades. Por ejemplo, eliminar las columnas con muchos datos faltantes (e.g. Awakenings y Caffeine compsumption) y recien luego de eso eliminar las filas que tengan algun dato perdido. 

De esa forma no pierdo tantas filas ni tantas columnas.

In [32]:
datos1 = datos.drop(columns=["Awakenings", "Caffeine consumption"])
datos2 = datos1.dropna()
datos2

# En un rato vamos a ver que hay formas más eficientes y ordenadas de encadenar comandos como estos.

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,1.0,Yes,3.0

Acá estoy llegando a un _"punto medio"_ entre perder observaciones y variables.

También podríamos elegir no eliminar los casos, sino reemplazar los datos faltantes con un valor (e.g. cero). A esto se lo llama "imputación de datos faltantes".

Lo podemos hacer con fillna()

In [33]:
datos.fillna(0)

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

In [34]:
# Chequeamos
filas_con_nan = datos.isna().any(axis=1)
datos[filas_con_nan]

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
5,6,36,Female,2021-07-01 21:00:00,2021-07-01 04:30:00,7.5,0.90,23,60,17,0.0,NaN,0.0,No,1.0
19,20,52,Male,2021-12-03 00:30:00,2021-12-03 07:30:00,7.0,0.89,28,52,20,NaN,50.0,0.0,Yes,3.0
20,21,24,Male,2021-05-02 00:00:00,2021-05-02 08:00:00,8.0,0.83,15,75,10,3.0,0.0,NaN,No,2.0
24,25,24,Male,2021-09-16 00:00:00,2021-09-16 07:00:00,7.0,0.88,15,75,10,1.0,NaN,5.0,No,2.0
26,27,36,Female,2021-06-18 00:00:00,2021-06-18 07:00:00,7.0,0.95,28,55,17,0.0,NaN,0.0,No,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,441,28,Female,2021-02-06 21:00:00,2021-02-06 05:00:00,8.0,0.88,22,63,15,0.0,75.0,NaN,Yes,2.0
442,443,27,Female,2021-02-06 01:30:00,2021-02-06 08:30:00,7.0,0.68,23,22,55,1.0,NaN,4.0,No,1.0
446,447,23,Male,2021-04-21 00:00:00,2021-04-21 07:00:00,7.0,0.50,15,40,45,2.0,0.0,4.0,Yes,NaN
449,450,40,Female,2021-09-07 23:00:00,2021-09-07 07:30:00,8.5,0.55,20,32,48,1.0,NaN,3.0,Yes,0.0
454,337,50,Female,2021-07-20 22:00:00,2021-07-20 05:00:00,7.0,0.90,22,58,20,1.0,0.0,NaN,No,5.0

In [35]:
datos0 = datos.fillna(0)
datos0[filas_con_nan]

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
5,6,36,Female,2021-07-01 21:00:00,2021-07-01 04:30:00,7.5,0.90,23,60,17,0.0,0.0,0.0,No,1.0
19,20,52,Male,2021-12-03 00:30:00,2021-12-03 07:30:00,7.0,0.89,28,52,20,0.0,50.0,0.0,Yes,3.0
20,21,24,Male,2021-05-02 00:00:00,2021-05-02 08:00:00,8.0,0.83,15,75,10,3.0,0.0,0.0,No,2.0
24,25,24,Male,2021-09-16 00:00:00,2021-09-16 07:00:00,7.0,0.88,15,75,10,1.0,0.0,5.0,No,2.0
26,27,36,Female,2021-06-18 00:00:00,2021-06-18 07:00:00,7.0,0.95,28,55,17,0.0,0.0,0.0,No,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,441,28,Female,2021-02-06 21:00:00,2021-02-06 05:00:00,8.0,0.88,22,63,15,0.0,75.0,0.0,Yes,2.0
442,443,27,Female,2021-02-06 01:30:00,2021-02-06 08:30:00,7.0,0.68,23,22,55,1.0,0.0,4.0,No,1.0
446,447,23,Male,2021-04-21 00:00:00,2021-04-21 07:00:00,7.0,0.50,15,40,45,2.0,0.0,4.0,Yes,0.0
449,450,40,Female,2021-09-07 23:00:00,2021-09-07 07:30:00,8.5,0.55,20,32,48,1.0,0.0,3.0,Yes,0.0
454,337,50,Female,2021-07-20 22:00:00,2021-07-20 05:00:00,7.0,0.90,22,58,20,1.0,0.0,0.0,No,5.0

¿Qué opinamos de esto? ¿Se puede usar en todos los casos? ¿Qué otras formas se te ocurren?

In [36]:
# Una forma super sencilla (pero no infalible) es reemplazar el dato perdido por la media o la mediana poblacional 
# (Capaz la mediana es mejor porque te va a buscar un dato existente)

# Ahora cual usamos??
#datos.fillna(mean)
#datos.fillna(datos.mean())

#Veamos el help... 
datos.fillna??

Signature:
datos.fillna(
    value: 'Hashable | Mapping | Series | DataFrame',
    *,
    axis: 'Axis | None' = None,
    inplace: 'bool' = False,
    limit: 'int | None' = None,
) -> 'Self'
Source:
    @final
    def fillna(
        self,
        value: Hashable | Mapping | Series | DataFrame,
        *,
        axis: Axis | None = None,
        inplace: bool = False,
        limit: int | None = None,
    ) -> Self:
        """
        Fill NA/NaN values with `value`.

        Parameters
        ----------
        value : scalar, dict, Series, or DataFrame
            Value to use to fill holes (e.g. 0), alternately a
            dict/Series/DataFrame of values specifying which value to use for
            each index (for a Series) or column (for a DataFrame).  Values not
            in the dict/Series/DataFrame will not be filled. This value cannot
            be a list.
        axis : {0 or 'index'} for Series, {0 or 'index', 1 or 'columns'} for DataFrame
            Axis along which to fill missing values. For `Series`
            this parameter is unused and defaults to 0.
        inplace : bool, default False
            If True, fill in-place. Note: this will modify any
            other views on this object (e.g., a no-copy slice for a column in a
            DataFrame).
        limit : int, default None
            This is the maximum number of entries along the entire axis
            where NaNs will be filled. Must be greater than 0 if not None.

        Returns
        -------
        Series/DataFrame
            Object with missing values filled.

        See Also
        --------
        ffill : Fill values by propagating the last valid observation to next valid.
        bfill : Fill values by using the next valid observation to fill the gap.
        interpolate : Fill NaN values using interpolation.
        reindex : Conform object to new index.
        asfreq : Convert TimeSeries to specified frequency.

        Notes
        -----
        For non-object dtype, ``value=None`` will use the NA value of the dtype.
        See more details in the :ref:`Filling missing data<missing_data.fillna>`
        section.

        Examples
        --------
        >>> df = pd.DataFrame(
        ...     [
        ...         [np.nan, 2, np.nan, 0],
        ...         [3, 4, np.nan, 1],
        ...         [np.nan, np.nan, np.nan, np.nan],
        ...         [np.nan, 3, np.nan, 4],
        ...     ],
        ...     columns=list("ABCD"),
        ... )
        >>> df
             A    B   C    D
        0  NaN  2.0 NaN  0.0
        1  3.0  4.0 NaN  1.0
        2  NaN  NaN NaN  NaN
        3  NaN  3.0 NaN  4.0

        Replace all NaN elements with 0s.

        >>> df.fillna(0)
             A    B    C    D
        0  0.0  2.0  0.0  0.0
        1  3.0  4.0  0.0  1.0
        2  0.0  0.0  0.0  0.0
        3  0.0  3.0  0.0  4.0

        Replace all NaN elements in column 'A', 'B', 'C', and 'D', with 0, 1,
        2, and 3 respectively.

        >>> values = {"A": 0, "B": 1, "C": 2, "D": 3}
        >>> df.fillna(value=values)
             A    B    C    D
        0  0.0  2.0  2.0  0.0
        1  3.0  4.0  2.0  1.0
        2  0.0  1.0  2.0  3.0
        3  0.0  3.0  2.0  4.0

        Only replace the first NaN element.

        >>> df.fillna(value=values, limit=1)
             A    B    C    D
        0  0.0  2.0  2.0  0.0
        1  3.0  4.0  NaN  1.0
        2  NaN  1.0  NaN  3.0
        3  NaN  3.0  NaN  4.0

        When filling using a DataFrame, replacement happens along
        the same column names and same indices

        >>> df2 = pd.DataFrame(np.zeros((4, 4)), columns=list("ABCE"))
        >>> df.fillna(df2)
             A    B    C    D
        0  0.0  2.0  0.0  0.0
        1  3.0  4.0  0.0  1.0
        2  0.0  0.0  0.0  NaN
        3  0.0  3.0  0.0  4.0

        Note that column D is not affected since it is not present in df2.
        """
        inplace = validate_bool_kwarg(inplace, "inplace")
        if inplace:
            if not CHAINED_WARNING_DISABLED:
                if sys.getrefcount(
                    self
                ) <= REF_COUNT_METHOD and not common.is_local_in_caller_frame(self):
                    warnings.warn(
                        _chained_assignment_method_msg,
                        ChainedAssignmentError,
                        stacklevel=2,
                    )

        if isinstance(value, (list, tuple)):
            raise TypeError(
                '"value" parameter must be a scalar or dict, but '
                f'you passed a "{type(value).__name__}"'
            )

        # set the default here, so functions examining the signature
        # can detect if something was set (e.g. in groupby) (GH9221)
        if axis is None:
            axis = 0
        axis = self._get_axis_number(axis)

        if self.ndim == 1:
            if isinstance(value, (dict, ABCSeries)):
                if not len(value):
                    # test_fillna_nonscalar
                    return self if inplace else self.copy(deep=False)
                from pandas import Series

                value = Series(value)
                value = value.reindex(self.index)
                value = value._values
            elif not is_list_like(value):
                pass
            else:
                raise TypeError(
                    '"value" parameter must be a scalar, dict '
                    "or Series, but you passed a "
                    f'"{type(value).__name__}"'
                )

            new_data = self._mgr.fillna(value=value, limit=limit, inplace=inplace)

        elif isinstance(value, (dict, ABCSeries)):
            result = self if inplace else self.copy(deep=False)
            if axis == 1:
                # Check that all columns in result have the same dtype
                # otherwise don't bother with fillna and losing accurate dtypes
                unique_dtypes = self._mgr.get_unique_dtypes()
                if len(unique_dtypes) > 1:
                    raise ValueError(
                        "All columns must have the same dtype, but got dtypes: "
                        f"{list(unique_dtypes)}"
                    )
                # Use the first column, which we have already validated has the
                # same dtypes as the other columns.
                if not can_hold_element(result.iloc[:, 0], value):
                    frame_dtype = unique_dtypes.item()
                    raise ValueError(
                        f"{value} not a suitable type to fill into {frame_dtype}"
                    )
                result = result.T.fillna(value=value).T
                if inplace:
                    self._update_inplace(result)
                    result = self
            else:
                for k, v in value.items():
                    if k not in result:
                        continue

                    res_k = result[k].fillna(v, limit=limit)

                    if not inplace:
                        result[k] = res_k
                    # We can write into our existing column(s) iff dtype
                    #  was preserved.
                    elif isinstance(res_k, ABCSeries):
                        # i.e. 'k' only shows up once in self.columns
                        if res_k.dtype == result[k].dtype:
                            result.loc[:, k] = res_k
                        else:
                            # Different dtype -> no way to do inplace.
                            result[k] = res_k
                    else:
                        # see test_fillna_dict_inplace_nonunique_columns
                        locs = result.columns.get_loc(k)
                        if isinstance(locs, slice):
                            locs = range(self.shape[1])[locs]
                        elif isinstance(locs, np.ndarray) and locs.dtype.kind == "b":
                            locs = locs.nonzero()[0]
                        elif not (
                            isinstance(locs, np.ndarray) and locs.dtype.kind == "i"
                        ):
                            # Should never be reached, but let's cover our bases
                            raise NotImplementedError(
                                "Unexpected get_loc result, please report a bug at "
                                "https://github.com/pandas-dev/pandas"
                            )

                        for i, loc in enumerate(locs):
                            res_loc = res_k.iloc[:, i]
                            target = self.iloc[:, loc]

                            if res_loc.dtype == target.dtype:
                                result.iloc[:, loc] = res_loc
                            else:
                                result.isetitem(loc, res_loc)
            return result

        elif not is_list_like(value):
            if axis == 1:
                result = self.T.fillna(value=value, limit=limit).T
                new_data = result._mgr
            else:
                new_data = self._mgr.fillna(value=value, limit=limit, inplace=inplace)
        elif isinstance(value, ABCDataFrame) and self.ndim == 2:
            new_data = self.where(self.notna(), value)._mgr
        else:
            raise ValueError(f"invalid fill value with a {type(value)}")

        result = self._constructor_from_mgr(new_data, axes=new_data.axes)
        if inplace:
            self._update_inplace(result)
            return self
        else:
            return result.__finalize__(self, method="fillna")
File:      ~/uba-compu-y-datos/laboratorio-de-datos-1c2026/.venv/lib/python3.14/site-packages/pandas/core/generic.py
Type:      method

In [37]:
# Tenemos que pasarle un vector de valores para usar en cada columna, el vector lo generamos asi:
datos.mean(numeric_only=True)   # No podemos tomar media de variables no-numericas

ID                        225.833333
Age                        40.222944
Sleep duration              7.470779
Sleep efficiency            0.787771
REM sleep percentage       22.614719
Deep sleep percentage      52.668831
Light sleep percentage     24.716450
Awakenings                  1.656109
Caffeine consumption       23.512586
Alcohol consumption         1.170022
Exercise frequency          1.800439
dtype: float64

Podemos resolverlo utilizando funciones que ya vimos, modificando la variable index.

In [38]:
# Esto va a funcionar?? fillna solo actúa en columnas numéricas??
datosMedia = datos.fillna(datos.mean(numeric_only=True))
datosMedia[filas_con_nan]

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
5,6,36,Female,2021-07-01 21:00:00,2021-07-01 04:30:00,7.5,0.90,23,60,17,0.000000,23.512586,0.000000,No,1.000000
19,20,52,Male,2021-12-03 00:30:00,2021-12-03 07:30:00,7.0,0.89,28,52,20,1.656109,50.000000,0.000000,Yes,3.000000
20,21,24,Male,2021-05-02 00:00:00,2021-05-02 08:00:00,8.0,0.83,15,75,10,3.000000,0.000000,1.170022,No,2.000000
24,25,24,Male,2021-09-16 00:00:00,2021-09-16 07:00:00,7.0,0.88,15,75,10,1.000000,23.512586,5.000000,No,2.000000
26,27,36,Female,2021-06-18 00:00:00,2021-06-18 07:00:00,7.0,0.95,28,55,17,0.000000,23.512586,0.000000,No,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,441,28,Female,2021-02-06 21:00:00,2021-02-06 05:00:00,8.0,0.88,22,63,15,0.000000,75.000000,1.170022,Yes,2.000000
442,443,27,Female,2021-02-06 01:30:00,2021-02-06 08:30:00,7.0,0.68,23,22,55,1.000000,23.512586,4.000000,No,1.000000
446,447,23,Male,2021-04-21 00:00:00,2021-04-21 07:00:00,7.0,0.50,15,40,45,2.000000,0.000000,4.000000,Yes,1.800439
449,450,40,Female,2021-09-07 23:00:00,2021-09-07 07:30:00,8.5,0.55,20,32,48,1.000000,23.512586,3.000000,Yes,0.000000
454,337,50,Female,2021-07-20 22:00:00,2021-07-20 05:00:00,7.0,0.90,22,58,20,1.000000,0.000000,1.170022,No,5.000000

En pocas palabras:
- Completamos con 0 si pensamos que no figura el dato porque no hay o no corresponde. Por ejemplo, en información de alimentos y bebidas, el porcentaje de alcohol puede figurar como NA.
- Completamos con el promedio si pensamos que se perdió el dato y queremos afectar lo menos posible los modelos (o una técnica más avanzada sería predecir ese valor usando otras variables).

Cómo completarías estos datos faltantes?
- Metros cuadrados de un departamento.
- Cantidad de votos recibidos por un partido en la elección anterior.
- Cantidad de ventas realizadas de cierto producto en cierto día.
- Altura de un paciente.

#### Ejercicio
1. Examinar el dataset de eficiencia MPG y hacer algo con los datos faltantes. ¿Qué harían si no queremos eliminar filas?
2. Examinar el dataset de pingüinos y hacer algo con los datos faltantes.

In [58]:
penguins = sns.load_dataset("penguins")
mpg = sns.load_dataset("mpg")

##### 1) Con MPG

In [59]:
mpg.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

Veo que solo hay datos faltantes en la variable de horsepower. Si no quiero eliminar filas puedo eliminar directamente la variable horsepower, pero estaría perdiendo mucha información.

In [60]:
filas_con_nan = mpg.isna().any(axis=1)
mpg[filas_con_nan]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
32,25.0,4,98.0,NaN,2046,19.0,71,usa,ford pinto
126,21.0,6,200.0,NaN,2875,17.0,74,usa,ford maverick
330,40.9,4,85.0,NaN,1835,17.3,80,europe,renault lecar deluxe
336,23.6,4,140.0,NaN,2905,14.3,80,usa,ford mustang cobra
354,34.5,4,100.0,NaN,2320,15.8,81,europe,renault 18i
374,23.0,4,151.0,NaN,3035,20.5,82,usa,amc concord dl

Veo que los datos faltantes de horsepower se dan en 4 autos de USA y 2 de Europa. Lo que voy a hacer es sacar la mediana de horsepower en cada origen y completar los datos faltantes con esos valores.

In [61]:
mpg_medianas_por_origen = mpg.groupby("origin").median(numeric_only=True)
mpg_medianas_por_origen

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
origin,,,,,,,
europe,26.5,4.0,104.5,76.5,2240.0,15.7,76.0
japan,31.6,4.0,97.0,75.0,2155.0,16.4,78.0
usa,18.5,6.0,250.0,105.0,3365.0,15.0,76.0

In [62]:
mediana_hp_usa = mpg_medianas_por_origen.horsepower.usa
mediana_hp_usa

np.float64(105.0)

In [63]:
mediana_hp_eu = mpg_medianas_por_origen.horsepower.europe
mediana_hp_eu

np.float64(76.5)

In [64]:
# Completo los datos faltantes y corroboro
mpg = mpg[mpg["origin"] == "usa"].fillna(mediana_hp_usa)
mpg = mpg[mpg["origin"] == "europe"].fillna(mediana_hp_eu)

mpg[filas_con_nan]

/tmp/ipykernel_42365/267017069.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  mpg[filas_con_nan]

Empty DataFrame
Columns: [mpg, cylinders, displacement, horsepower, weight, acceleration, model_year, origin, name]
Index: []

### 2.b Eliminar datos duplicados

En muchos casos puede suceder que haya datos duplicados en nuestro dataset. ¿Se les ocurren ejemplos?

Para identificarlos, podemos usar `duplicated()`. ¿Qué está haciendo esta función?

In [ ]:
datos.duplicated()

In [ ]:
# Cuántos datos duplicados hay?
datos.duplicated().sum()

In [ ]:
# Es la misma fila repetida muchas veces o varias filas duplicadas?
# Podemos usar el viejo y querido value_counts()...
datos.value_counts()

Para eliminarlos, podríamos usar `drop_duplicates()`

In [ ]:
# O vemos las filas
datos[datos.duplicated()]

# O keep = False para ver todas las filas duplicadas, todas las veces que aparecen
datos[datos.duplicated(keep = False)]

In [ ]:
# Eliminamos duplicados
datos.drop_duplicates()

¿Qué hace esta función? ¿Qué valores se queda y cuáles elimina?

Por defecto, se queda con el primer caso, pero podemos indicarle que se quede con el último por ej:

In [ ]:
datos.drop_duplicates(keep = "last")

**Pregunta:** Si tuvieramos sujetos duplicados, es decir, completaron dos veces la misma encuesta, pero respondieron distinto, cómo lo podríamos saber?

### 2.c Resetear el index

Volvamos a los pingüinos.
Una vez que eliminamos filas por el motivo que sea, nos van a quedar índices salteados. En muchos casos no es importante conservar los índices originales, y es conveniente numerar todo de 0 a N-1.

In [ ]:
penguinsClean = penguins.dropna()
penguinsClean

In [ ]:
# Reseteamos los índices 
penguinsClean = penguinsClean.reset_index()
penguinsClean   # Vemos que creó una nueva columna con los índices viejos

In [ ]:
# De esta forma solo nos quedamos con lo síndices nuevos.
penguinsClean = penguinsClean.reset_index(drop = True)
penguinsClean

In [ ]:
# No funciono??
# Es que tenemos que empezar todo de nuevo!

penguinsClean = penguins.dropna()
penguinsClean = penguinsClean.reset_index(drop = True)
penguinsClean

## Encadenar todos estos métodos

Esta forma de ir modificando un dataset no es muy práctica.

Por ejemplo si ejecutamos varias veces el mismo comando, obtendremos cada vez algo distinto.

Una solución es encadenar métodos para hacer el código más legible y fácil de reusar. Y más eficiente también.

In [ ]:
penguinsClean = penguins.dropna().reset_index()
penguinsClean.head()

In [ ]:
# Si queremos eliminar la columna de índices viejos
penguinsClean = penguins.dropna().reset_index(drop = True)
penguinsClean.head()

In [ ]:
# Ahora sumamos 1 a todos los indices
penguinsClean.index += 1
penguinsClean.head()

Podemos encadenar estas operaciones?

In [ ]:
penguinsClean = penguins.dropna().reset_index(drop = True).index += 1

In [ ]:
# Eso dio error. Y así?
penguins.dropna().reset_index(drop = True).index += 1
penguins.head()

No sabemos dónde lo guardó...

Para encadenar esta operación vamos a utilizar `.rename(index = dict o function)`.

Podemos pasarle también un diccionario o una función.

### Ejercicio 
1. Cambiar el índice 0 a "Cero".
2. Tomas la raíz cuadradada de los índices (del dataset penguinsClean original sin "Cero").

In [ ]:
penguinsClean = penguins.dropna().reset_index(drop = True)
penguinsClean.head()

### Ejemplo: sumar uno a todos los índices

Para sumar uno a todos los índices no podemos hacer penguinsClean.rename(index = + 1).

Podemos definir primero nuestra propia función.

In [ ]:
def sumaUno(x):
    return(???)

penguinsClean.rename(index = ???)

## 3. Funciones lambda
Resulta engorroso definir una función para usarla solamente dentro del rename. 

Las **funciones lambda** nos permiten definir funciones anónimas "al vuelo".

La sintaxis es

`lambda arguments : expression`

In [ ]:
# Ejemplo
x = lambda a : a + 10
print(x(5))

In [ ]:
# Ejemplo
x = lambda a, b : a * b
print(x(5, 6))

In [ ]:
# Ejemplo
x = lambda a : a + 1
print(x(5))

In [ ]:
# Ahora sí!
penguinsClean.rename(index = lambda a : a + 1)

Esta operación la podemos encadenar con las anteriores:

In [ ]:
penguinsClean = penguins.dropna().reset_index(drop = True).rename(index = lambda a : a + 1)
penguinsClean.head()

In [ ]:
# O si queremos cada metodo en una linea nueva
penguinsClean = (
    penguins.dropna()
    .reset_index(drop = True)
    .rename(index = lambda a : a + 1)
)
penguinsClean.head()

### Ejercicio
Utilizando funciones lambda:
1. Encadenar un método más para agregar "_orig" a los nombres de todas las columnas.
2. Encadenar un método más para reemplazar todos _ por - en los nombres de columnas.

In [ ]:
# Sugerencia 1
"hola" + "chau"

In [ ]:
# Sugerencia 2
str.replace("abcndjaA", "a", "oo")